# The tested JetPack versions.
ALLOWED_L4T_VERSIONS:
  - 35.3.1
  - 35.4.1
  - 35.5.0
  - 36.3.0
  - 36.4.0
REQUIRED_DISK_SPACE: 15
REQUIRED_MEM_SPACE: 7
PACKAGES:
  - nvidia-jetpack
DOCKER: 
  ENABLE: true
  DAEMON: |
    {
      "default-runtime": "nvidia",
      "runtimes": {
        "nvidia": {
          "path": "nvidia-container-runtime",
          "runtimeArgs": []
        }
      },
      "storage-driver": "overlay2",
      "data-root": "/var/lib/docker",
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m",
        "max-file": "3"
      },
      "no-new-privileges": true,
      "experimental": false
    }
