allowed_l4t_versions:
  - 35.3.1
  - 35.4.1
  - 35.5.0
required_disk_space: 20  # in GB
min_mem_gb: 4
min_swap_gb: 2
nvidia_jetson_package: "nvidia-jetpack"
packages:
  #- "ros-noetic-ros-base"
  #- "flask"
docker:
  desired_daemon_json: |
    {
      "default-runtime": "nvidia",
      "runtimes": {
        "nvidia": {
          "path": "nvidia-container-runtime",
          "runtimeArgs": []
        }
      },
      "storage-driver": "overlay2",
      "data-root": "/var/lib/docker",
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m",
        "max-file": "3"
      },
      "no-new-privileges": true,
      "experimental": false
    }
