ALLOWED_L4T_VERSIONS:
- 35.3.1
- 35.4.1
- 35.5.0
- 36.2.0
- 36.3.0
- 36.4.0
- 36.4.3
- 36.4.4
REQUIRED_DISK_SPACE: 80
REQUIRED_MEM_SPACE: 15
PACKAGES:
- nvidia-jetpack
DOCKER:
  ENABLE: true
  DAEMON: "{\n  \"default-runtime\": \"nvidia\",\n  \"runtimes\": {\n    \"nvidia\"\
    : {\n      \"path\": \"nvidia-container-runtime\",\n      \"runtimeArgs\": []\n\
    \    }\n  },\n  \"storage-driver\": \"overlay2\",\n  \"data-root\": \"/var/lib/docker\"\
    ,\n  \"log-driver\": \"json-file\",\n  \"log-opts\": {\n    \"max-size\": \"100m\"\
    ,\n    \"max-file\": \"3\"\n  },\n  \"no-new-privileges\": true,\n  \"experimental\"\
    : false\n}\n"
